ktor:
  application:
    modules:
      - bazydanych.ApplicationKt.publicApi
  deployment:
    port: 8080
jwt:
  realm: "bazydanych"
  secret: "xyz"
  issuer: "https://bazydanych.fun/"

postgres:
  url: "jdbc:postgresql://192.168.100.13:5432/workshop"
  user: "workshop"
  password: "xxx"
